ms-iot/ros-windows-build

ros-colcon-build/crystal/azure-pipelines.yml

Some repositories for Crystal branch (`rcl`) still hit build breaks on msvc2019, so revert back to use msvc2017 instead.

Revert back to use msvc2017 for Crystal build.

---

ros-catkin-build/azure-pipelines.yml

This is to address the out-of-space issue on CI agent.

Clean agent before building.

---

ros-catkin-build/melodic/runtests.rosinstall

The following repos are fully upstream'ed, so we no longer need to patch it with our `ms-iot` forks:
* https://github.com/ros-perception/laser_geometry
* https://github.com/ros-perception/laser_assembler
* https://github.com/ros-perception/laser_filters

Upstream repositories cleanup for melodic run_tests build

---

ros-catkin-build/azure-pipelines.yml
ros-catkin-build/melodic/build.rosinstall

Switched to use `ms-iot\msft_ros_pkgs` for Vcpkg integration.

Use ms-iot msft_ros_pkgs for Vcpkg integration

---

ros-catkin-build/azure-pipelines.yml

The recent viz build is broken because a recent addition of `roslint` to `package.xml` which adds the inconsistent dependency graph between `rosdistro` data and the upstream source file. To work around the issue before the changes are released to `rosdistro`, I added `roslint` to fix the build.

Fix a recent build break in viz build

---

ros-colcon-build/melodic/build.rosinstall

The diff has been merged on the upstream, so we don't need the override.

Use upstream catkin.

---

common/rospkg2cgmanifest.py
ros-catkin-build/azure-pipelines.yml
ros-catkin-build/common/cgscan.yml

Add script to enumerate the installed ROS packages and generate `cgmanifest.json` and also do a `pip freeze` to dump installed `pip` packages for component governance inventory.

Add component scanning for ROS and pip packages.

---

rosdep/cgmanifest.json

* Use the license ID from https://spdx.org/licenses/ to help component governance automation.
* Fix Git URL for `pyside2`.

Updated license ID for standard-conforming.

---

docker/azure-pipelines.yml

Per MCR's team feedback, we should move the OS names into tags. (One example is https://hub.docker.com/_/microsoft-dotnet-core-sdk/)

[dockerized ROS] Moved the OS names into tags.

---

rosdep/cgmanifest.json

Per Open Source team's suggestion, use `other` for `PySide2` registration so the back-end can identify the software license correctly.

[component governance] update PySide2 registration 

---

ros-catkin-build/azure-pipelines.yml
ros-catkin-build/ros-melodic-desktop.runtests.yml
ros-catkin-build/ros-melodic-desktop_full.runtests.yml
ros-catkin-build/ros-melodic-ros_base.runtests.yml
ros-colcon-build/crystal/azure-pipelines.yml
ros-colcon-build/dashing/azure-pipelines.yml
ros-colcon-build/melodic/azure-pipelines.yml

A recent change in `catkin`(https://github.com/ros/catkin/pull/1025) starts to use `ROS_PYTHON_VERSION` to conditionally pick & choose Python dependencies. Consequently, the environment variables becomes mandatory to build ROS from source.

[catkin] Add ROS_PYTHON_VERSION for python conditional dependencies

---

docker/azure-pipelines.yml

This is to address a feedback from MCR team, which suggests to have a more generic product family name prefix in front of `ros`.

[dockerized] Prefix the container repository name as robotics.

---

ros-catkin-build/melodic/build.rosinstall

To override the `qt_gui_core` for melodic build to rescue the build before the fix gets merged at upstream. https://github.com/ros-visualization/qt_gui_core/pull/188

override qt_gui_core before fix gets upstream'ed.

---

ros-colcon-build/eloquent/azure-pipelines.yml
ros-colcon-build/eloquent/build.rosinstall
ros-colcon-build/eloquent/rosdep.bat

- Add the initial Eloquent build pipeline.
- Skip the broken packages and they require more effort to bring up for ROS2 Windows:
- gazebo_ros
- theora_image_transport
- cartographer
- ros_workspace
- depthimage_to_laserscan
- camera_info_manager
- teleop_twist_joy
- Override the following packages before the fix pull requests are merged at the upstream:
- pluginlib
- vision_opencv
- image_common
- rviz

Add initial Eloquent build pipeline.

---

ros-catkin-build/melodic/runtests.rosinstall
ros-colcon-build/melodic/build.rosinstall

They are missing from this [pull request](https://github.com/ms-iot/ros-windows-build/pull/20) and required to recover the test build (and the melodic on Python3 experimental build.)

Add qt_gui_core override to recover builds.

---

ros-colcon-build/noetic/azure-pipelines.yml
ros-colcon-build/noetic/build.rosinstall
ros-colcon-build/noetic/rosdep.bat

- On-boarding the initial `noetic` build pipelines.
- The `build.rosinstall` is generated manually since none of any packages yet are released from [`rosdistro`](https://github.com/ros/rosdistro) and by default `rosinstall_generator` doesn't generate the entries for `unreleased` packages. The list should be removed in future as `noetic` project progresses.
- Two repositories are overridden with `ms-iot` repos: (There are Windows build breaks and wait for the upstream to merge the fixes.)
- `rospack` (https://github.com/ros/rospack/pull/108)
- `qt_gui_core` (https://github.com/ros-visualization/qt_gui_core/pull/188)
- Skip `nodelet_topic_tools` packages since there is some `Python3` compatibility issues blocking the build.

Add initial noetic build pipeline.

---

ros-colcon-build/dashing/build.rosinstall
ros-colcon-build/eloquent/azure-pipelines.yml
ros-colcon-build/eloquent/build.rosinstall

- Removed `ms-iot` repositories override since the patches are merged at the upstream:
- `depthimage_to_laserscan`
- `pluginlib`
- `image_common`
- Consolidate the override across ROS `distro` since they are pointed to the same branches:
- `vision_opencv`
- `rviz`

cleanup by removing staging repositories.

---

ros-colcon-build/dashing/build.rosinstall
ros-colcon-build/eloquent/build.rosinstall

The patches for `vision_opencv` are merged just an hour ago at the upstream. :)

remove vision_opencv override.

---

ros-catkin-build/melodic/build.rosinstall
ros-catkin-build/melodic/runtests.rosinstall
ros-colcon-build/melodic/build.rosinstall
ros-colcon-build/noetic/build.rosinstall

The rework [patch](https://github.com/ros-visualization/qt_gui_core/pull/188) for `qt_gui_core` is merged at the upstream.

remove ms-iot qt_gui_core override.

---

ros-colcon-build/melodic/azure-pipelines.yml
ros-colcon-build/noetic/azure-pipelines.yml

As there are more `Python3` convention has been discussed and implemented, I believe we should follow the same [guidance](https://github.com/ros-infrastructure/rep/pull/201) to maintain the `rosdep` database. And this pull request is part of the effort to start converge the `init_windows_py37` and `init_windows` branch.
Once I stabilize `Python3` builds for `ROS1`. I will expand the convergence to `ROS2` builds.

Consolidate py3 & py2 rosdep database for ROS1 builds.

---

ros-colcon-build/dashing/build.rosinstall

The `ros2` branch for `rviz` is no longer commonly shared for `dashing` and `eloquent`, so I made a branch plus a patch to rescue the `dashing` build.

Fix dashing build break.

---

ros-catkin-build/melodic/build.rosinstall

Use the last stable released `catkin`. The latest code on the upstream seems to come with problems and I am confirming with the package owner.

[catkin][melodic] Fixed build break

---

ros-colcon-build/eloquent/azure-pipelines.yml
ros-colcon-build/eloquent/build.rosinstall

* skip `ecl_type_traits` before Windows enablement.
* remove `rviz` since now the patch is merged back on the upstream.

[colcon][eloquent] skip ecl_type_traits before Windows enablement.

---

ros-catkin-build/melodic/build.rosinstall

Switch back to use the upstream catkin since a recent regression is fixed. https://github.com/ros/catkin/pull/1041

[catkin][melodic] use the upstream catkin.

---

ros-catkin-build/melodic/build.rosinstall

Lock the eigenpy to v1.6.6 which is the LKG release for Windows.

Lock the eigenpy to v1.6.6

---

package-build/build.bat

`ROS_PYTHON_VERSION` is a environment variable, which is defined in [REP-149](https://www.ros.org/reps/rep-0149.html), to bootstrap the ROS tools (for example, `rosdep`) to use the correct conditional dependencies for the installation.
We already use it in the build pipeline. And we should also prime it for packaging, so the install script can inference the correct dependencies (see [examples](https://github.com/ros/ros_comm/blob/melodic-devel/tools/rosmaster/package.xml)) during installation. This pull request is to add the missing piece.

Add ROS_PYTHON_VERSION for installation.

---

ros-catkin-build/melodic/build.rosinstall
ros-colcon-build/melodic/build.rosinstall

The [`ros_control`](https://github.com/ros-controls/ros_control) recently has a [change](https://github.com/ros-controls/ros_control/commit/10ff185bc31113ca434e3169e0e3b66193f4eef8) which could lead to a namespace conflicts with `ERROR` defined from `Windows` header. I locked the `ros_control` to the LKG revision before a solution is concluded.

[melodic] lock ros_control to the LKG revision.

---

common/agent-clean.yml
common/remove-unused-toolchains.bat

The out-of-space incidents happened more often last week, I tried to remove more unused tools to reclaim the space for build.

[common] Reclaim more disk space for build.

---

ros-catkin-build/melodic/runtests.rosinstall

The pending PR of `filter` is merged by the upstream.

remove filter override.

---

ros-catkin-build/melodic/build.rosinstall

The change is merged by the upstream, so we remove the override.

[melodic] remove ros_comm override.

---

ros-colcon-build/melodic/build.rosinstall
ros-colcon-build/noetic/build.rosinstall

The fix is merged by the upstream.

[common] remove geometry2 override.

---

ros-catkin-build/melodic/build.rosinstall

temp override geometry2 since a recent change from the upstream breaking `moveit` build.

[melodic] temp fix a recent regression.

---

ros-catkin-build/setup.bat
ros-colcon-build/setup.bat

Unsetting `%Boost_ROOT%` to prevent from picking the wrong `Boost` on the build agent.

[common] unset Boost_ROOT

---

ros-catkin-build/setup.bat
ros-colcon-build/setup.bat

More fixes to unset the Boost global override to make the build pick up the correct Boost.

[common] Unset Boost global override on hosted agent.

---

ros-catkin-build/azure-pipelines.yml
ros-catkin-build/build.bat
ros-catkin-build/build_test.bat
ros-catkin-build/common/checkout.yml
ros-catkin-build/melodic/build.rosinstall
ros-catkin-build/melodic/runtests.rosinstall
ros-catkin-build/ros-melodic-desktop.runtests.yml
ros-catkin-build/ros-melodic-desktop_full.runtests.yml
ros-catkin-build/ros-melodic-ros_base.runtests.yml
ros-colcon-build/melodic/azure-pipelines.yml

Since many of the repositories are merged by the upstream, I decided to switch `melodic` build to directly point to the upstream `rosdistro` and only override the repos required.
It means we don't need to process distribution file in [rosdistro-db](https://github.com/ms-iot/rosdistro-db/tree/init_windows) to keep it in sync, and the upstream one is the only source of truth.

[melodic] switch to use upstream rosdistro

---

ros-catkin-build/melodic/build.rosinstall

The upstream source has been added to the upstream rosdistro, so we can remove the override here. (https://github.com/ros/rosdistro/pull/23819)

[melodic] remove cartographer override.

---

README.md
ros-colcon-build/foxy/azure-pipelines.yml

[`ros_workspace`](https://github.com/ros2/ros_workspace) is a package which is designed for Debian packaging experience, and which doesn't compile on Windows build. For now I skip this package to unblock the build break.

[foxy] skip ros_workspace to unblock the build breaks.

---

ros-catkin-build/melodic/build.rosinstall

This reverts commit 18db8913cbe7531f8a4b2ccb4be27e4c476ae1ae, in response to https://github.com/ros/rosdistro/pull/23827.

Revert "[melodic] remove cartographer override. (#67)"

---

ros-catkin-build/melodic/build.rosinstall

The patches are merged by the upstream, so we removed the `ms-iot` override.

[melodic] remove rosserial override.

---

package-build/tools/chocolateyInstall.ps1
package-build/tools/rosdepInstall.bat
ros-catkin-build/azure-pipelines.yml
ros-colcon-build/crystal/azure-pipelines.yml
ros-colcon-build/dashing/azure-pipelines.yml
ros-colcon-build/eloquent/azure-pipelines.yml

* Adding the error check for `rosdep install`, so the failure can propagate to `Chocolatey`.
* Unify all rosdep database to use the same file for ROS1 and ROS2.
* Test the install to `desktop` (or `desktop_full`) variant if it exists.

Adding error handling for rosdep install step

---

ros-colcon-build/crystal/rosdep.bat
ros-colcon-build/dashing/rosdep.bat
ros-colcon-build/eloquent/rosdep.bat
ros-colcon-build/foxy/rosdep.bat

There are some [`Modules`](https://cmake.org/cmake/help/v3.17/release/3.17.html#modules) changes in CMake 3.17 breaking the ROS build, so pinning the cmake to the previous LKG version to unblock it.

[ros2] pinning cmake to the LKG version.

---

package-build/template.nuspec

Be explicit to specify the vcredist deps from the root package, instead of depending on the deps resolved by the `rosdep` (which is vulnerable for changes).

[packaging] explicit to specify the vcredist deps from the root package.

---

ros-colcon-build/foxy/azure-pipelines.yml

`librealsense2` causes the build break on CI. Since it is not an essential package, I take it offline for now.

[foxy] ignore librealsense2 for now.

---

package-build/tools/vcpkgInstall.ps1

`Git` generates warning even when `-q` is in use. Redirect the output to `Out-null` to avoid `PowerShell` treats it as `Error`.

[common] Fix build break.

---

ros-catkin-build/melodic/build.rosinstall

* Override `rviz` and `cartographer` to for the relocatable testing.
* Change to use the new organization account `cartographer-project` for `cartographer` repos.

[melodic] override for relocatable testing.

---

ros-catkin-build/melodic/build.rosinstall

Trying to drop the full path of `rpcrt4.lib` being baked into the auto-generated CMake config files. For example, we don't want `C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x64/RpcRT4.Lib` baked in the `bondcpp-config.cmake` and we want the CMake config to be more resilient to Windows SDK versions.

[melodic] override cmake_modules

---

ros-colcon-build/eloquent/build.rosinstall

removing the fast-rtps pinning and use the latest from the upstream.

[eloquent] remove fast-rtps pinning.

---

gazebo/gazebo9/azure-pipelines.yml

override `ign-cmake` to include this patch https://github.com/ms-iot/ign-cmake/commit/a13f2695cf4bed4c514ef0e5b8a5536c83c11c47 to avoid `gazebo_ros_pkgs` build breaks on ROS2 side.

[gazebo9] override ign-cmake

---

ros-catkin-build/azure-pipelines.yml
ros-catkin-build/build.bat
ros-catkin-build/build_test.bat
ros-colcon-build/build.bat
ros-colcon-build/crystal/azure-pipelines.yml
ros-colcon-build/dashing/azure-pipelines.yml
ros-colcon-build/eloquent/azure-pipelines.yml
ros-colcon-build/foxy/azure-pipelines.yml
ros-colcon-build/noetic/azure-pipelines.yml

For the Gazebo v9.13.1, it requires the CMake to give it hint where the protobuf compiler is from `CMAKE_PROGRAM_PATH`.

[common] Adding CMAKE_PROGRAM_PATH to make protobuf compiler visible for build.

---

ros-catkin-build/melodic/build.rosinstall

A recent change in the [`cartographer_ros`](https://github.com/cartographer-project/cartographer_ros/commit/be4332b3385b5eea2511d11de5cc6792ecb4af2e) breaks builds on Windows. Use the LGK build.

[melodic] use the LKG cartographer_ros.

---

ros-colcon-build/common/checkout.yml
ros-colcon-build/common/runtests.yml
ros-colcon-build/dashing/azure-pipelines.yml
ros-colcon-build/eloquent/azure-pipelines.yml
ros-colcon-build/foxy/azure-pipelines.yml
ros-colcon-build/noetic/azure-pipelines.yml

* Address the typo to cause build breaks.
* Conditionally control the testing runs.
* Address a regression to `noetic` build breaks when we still expect to use the upstream branch.

[ROS2] more fixes.

---

ros-colcon-build/noetic/build.rosinstall

* A recent change in the https://github.com/ros/diagnostics.git caused Windows side build break. Before figuring out the right way to resolve it, pin it back to the LKG.
* Patched the pluginlib to enable plugin loading.

[Noetic] Fixing noetic build break.

---

package-build/tools/rosdepInstall.bat
ros-catkin-build/melodic/build.rosinstall

* Fixing the recent installation break caused by `opencv-python`.
* Removing the unused repo override.

[Melodic] Fix recent installation break

---

package-build/package-test-upgrade.yml

To accommodate the case where the current LKG install broken, this will continue to test the upgrade path but there will be a warning (!) on the pipeline result. And it leaves the final adjudication to the release developers.

[Common] Continue even when LKG install fails.

---

ros-colcon-build/eloquent/azure-pipelines.yml
ros-colcon-build/foxy/azure-pipelines.yml

Updating `Foxy` and `Eloquent` release snapshots. 
* `Foxy`: `20200710` -> `20200807`
* `Eloquent`: No actual content change. Simply use the correct tag. There was one tag created in a wrong name from the upstream.

[ROS2] update the release snapshots

---

ros-colcon-build/eloquent/rel.rosinstall

Use the LKG osrf_testing_tools_cpp.

[Eloquent] Fixing osrf_testing_tools_cpp build breaks.

---

experimental/ros/noetic/noetic_override.repos

This should be able to removed in the next Noetic release sync. This time we hand picked it to unblock downstream packages which consumed the `dynamic_reconfigure` generated C++ headers.

[noetic] Use dynamic_reconfigure v1.7.1 to workaround dynamic_reconfigure Python3 compatibility.

---

experimental/ros/dashing/setup.iss
experimental/ros/eloquent/setup.iss

Use the same naming convention like what we did for Noetic and Foxy.

[vNext] Normalize the naming convention for the installer EXE.

---

experimental/ros/azure-pipelines.dashing.release.yml
experimental/ros/azure-pipelines.eloquent.release.yml

* On Eloquent and Dashing, the cv_bridge is only compatible with OpenCV3. (Our Vcpkg recipe currently is using OpenCV4)
* And there is a build breaks in the camera_calibration_parsers when it tries to include YAML-cpp. The error looks like because there are two copies of YAML-cpp which are not compatible resulting in compile errors. I think we need a back-port of [this](https://github.com/ros2/yaml_cpp_vendor/commit/b11d00fbbe2cd8c8888f8c11ff172e84fdea9adc) for Eloquent and Dashing. For now just disable it to unblock the build.

[Eloquent][Dashing] Ignore cv_bridge camera_calibration_parsers for now

---

experimental/ros/azure-pipelines.dashing.release.yml
experimental/ros/azure-pipelines.eloquent.release.yml
experimental/ros/azure-pipelines.foxy.release.yml
experimental/ros/azure-pipelines.noetic.release.yml
experimental/ros/azure-pipelines.publish.prerelease.yml
experimental/ros/azure-pipelines.publish.release.yml

Separate the deployment by release types, so approval goes to individual types.

[vNext] Separate the deployment by release types.

---

experimental/ros/azure-pipelines.dashing.release.yml
experimental/ros/azure-pipelines.eloquent.release.yml
experimental/ros/azure-pipelines.foxy.release.yml
experimental/ros/azure-pipelines.noetic.release.yml
experimental/ros/azure-pipelines.packaging.yml

After this pull request (https://github.com/ms-iot/ros-windows-build/pull/134), the package names are getting lost between the changes. This change is to correct it back.

[vNext] Correcting the package names from a earlier refactoring

---

experimental/ros/melodic/patch/etc/catkin/profile.d/999.sdformat.bat

`SDF_PATH` is required after the `sdformat` binary relocation.

[vNext][Melodic] Adding the SDF_PATH.

---

experimental/ros/foxy/foxy_override.repos

The [gtest fix](https://github.com/ament/ament_cmake/pull/267) is in the upstream but there are 2 version away from the one Foxy used. This pull request is a cherry-pick to ingest the fix and this will make the first time dev experience better.

[vNext] [Foxy] cherry-pick gtest fix from ament_cmake.

---

experimental/external/melodic/bootstrap.ps1

Place `graphviz` utilities into the tools folder since it comes with its dependent DLLs and some are colliding with other deps (E.g. `cairo`.)

[vNext][Melodic] Place graphviz binaries into the tools folder.

---

experimental/ros/azure-pipelines.noetic.release.yml
experimental/ros/noetic/build.bat
experimental/ros/noetic/pre-patch/etc/catkin/profile.d/999.sdformat.bat
experimental/ros/noetic/src/gazebo/gazebo10/colcon.pkg
experimental/ros/noetic/src/gazebo_ros_pkgs/gazebo_dev/colcon.pkg
experimental/ros/noetic/src/msft_ros_env/CMakeLists.txt
experimental/ros/noetic/src/msft_ros_env/LICENSE
experimental/ros/noetic/src/msft_ros_env/env-hooks/sdformat.bat.in
experimental/ros/noetic/src/msft_ros_env/env-hooks/vcpkg.bat.in
experimental/ros/noetic/src/msft_ros_env/package.xml

`Colcon` is discovering the catkin hooks in a different path. Opposing to just drop the hooks file in `etc/catkin/profile.d`,  adding those hooks by `catkin` package can make those hooks get injected into the proper location by the build tool.

[vnext][noetic] Adding msft_ros_env for colcon\catkin hooks.

---

experimental/ros/noetic/build.bat
experimental/ros/noetic/patch.bat
experimental/ros/noetic/pre-patch/etc/ros/rosdep/windows.yaml

* Add rosbridge related dependencies.
* Edit the `rosdep\windows.yaml` to reflect the mapping.
* Remove some Linux-specific bash scripts under `%INSTALL_DIR%\Lib\rosbridge_server\` which confused the roslaunch on what to run.

[Noetic] Patch rosbridge dependencies.

---

experimental/ros/melodic/melodic_override.repos
experimental/ros/noetic/noetic_override.repos

https://github.com/ms-iot/cartographer_ros/commit/ed8bb191baff4875b498a97c1ecd45d4d000c07c
https://github.com/ms-iot/cartographer_ros/commit/7b610cc42dc3d1844675cabf9f8e352c491b4aab
The details can be found in cartographer-project/cartographer#1026. This is not a platform specific issue.
In short, in ROS1, there is no guarantee that the messages will be delivered in chronological order (in terms of the timestamp), and when it happens, cartographer treats it as fatal error and aborts the running process. It essentially stops the SLAM process, and currently no workaround to this situation.
This is discovered and tested on LattePanda + TurtleBot3 Burger by running Cartographer SLAM.

[melodic][noetic] Patch release for cartographer_ros

---

external/azure.pipelines.external.yml

This is a preparation step to create the `rolling` distro from the external matrix, so later the `rolling` pipeline can consume its own external dependency.

Provision rolling external in the build matrix.

---

ros/foxy/foxy_override.md
ros/foxy/foxy_override.repos

Windows fixes are in for moveit2 upstream. The override can now point to the upstream at a commit with the fixes.
Once the release tag is updated to include the fixes we can remove the override entirely.

Point to upstream moveit2 for override.

---

ros/foxy/patch.bat

When running 6.1.0 or later, pytest fails to load due to a dependency on result log.
https://github.com/pytest-dev/pytest-rerunfailures/issues/128

Pin pytest
