- docker/azure-pipelines.yml
- docker/daemon.json
- docker/garbage-collection.ps1
- docker/garbage-collection.yml
- docker/melodic/windowsservercore/desktop-full/dockerfile
Initial check-in for containerized ROS image build pipeline for `ROS on Windows`.
* `docker/azure-pipelines.yml` is the entry point to build containerized ROS images.
* `docker/garbage-collection.yml` is the maintenance pipelines to remove non-tagged images to release unused space from container registry.
> Add containerized ROS image build pipeline.

- docker/garbage-collection.ps1
`Azure CLI` returns a `JSON` string with a array `[...]` as the root, and in such case `ConverFrom-Json` returns a 2-D array and we should iterate the inner one to get the correct values.
> Enumerate the objects at the correct loop.

- rosdep/cgmanifest.json
Inventory the system libraries for rosdep (up to `desktop_full`), which will be consumed by component governance tool automatically.
> Add cgmanifest.json for rosdep components

- ros-catkin-build/azure-pipelines.yml
- sfx-installer/build.yml
Add job to create 7zip SFX installer for ROS installation.
> [ros-catkin-build] add job to create SFX installer.

- ros-colcon-build/eloquent/azure-pipelines.yml
Enable metapackages build matrix.
> [eloquent] Enable metapackages build matrix.

- ros-colcon-build/noetic/build.rosinstall
The patch is merged by the upstream.
> [colcon][noetic] use upstream rospack.

- ros-catkin-build/azure-pipelines.yml
- ros-catkin-build/melodic/build.rosinstall
Add `imu_tools` into `desktop` and `desktop_full` for handy access.
> Add imu_tools into desktop and desktop_full

- gazebo/gazebo9/azure-pipelines.yml
- gazebo/gazebo9/build.bat
- gazebo/gazebo9/copy_binaries.ps1
Moved the Gazebo9 build pipeline into `ros-windows-build`.
> [Gazebo] Add gazebo9 build pipeline.

- ros-colcon-build/eloquent/build.rosinstall
Apply the patch for this problem: https://github.com/eProsima/Fast-RTPS/issues/927
> [eloquent] patch fastrtps <thr/xthreads.h> build failure.

- ros-catkin-build/melodic/build.rosinstall
- ros-colcon-build/melodic/build.rosinstall
Override `gazebo_ros_pkgs` with a temp fix, before a proper fix has been resolved at `Gazebo` header.
https://github.com/ms-iot/gazebo_ros_pkgs/commit/364e9f1d3d0e6cb745b3868f3b16f2a3f6e0d3ef
> [melodic] override gazebo_ros_pkgs with a temp fix.

- ros-colcon-build/noetic/build.rosinstall
- bulk updated repos with the latest `rosdistro`.
- replaced some not-yet-upstream repos with the ones under `ms-iot`.
> [noetic] bulk update repos with the 2020/01/14 rosdistro

- README.md
add build badges to README.md for quick look up.
> [build badges] Add build badges in README.md

- ros-colcon-build/common/runtests.yml
- ros-colcon-build/dashing/azure-pipelines.yml
- ros-colcon-build/setup.bat
- ros-colcon-build/test.bat
* Enabling test pass for `eloquent` and collect results.
> [eloquent] Enable test pass and collect results

- ros-catkin-build/melodic/build.rosinstall
This is one missing entry I forgot to move from `rosdistro-db`.
> [melodic] override the soem.

- ros-catkin-build/melodic/build.rosinstall
The changes are merged by the upstream repository so we can remove the override.
> [melodic] removed the urdf override.

- ros-catkin-build/melodic/build.rosinstall
removing merged forks: `gencpp`, `navigation`.
> [melodic] removing merged forks.

- ros-catkin-build/melodic/build.rosinstall
> [melodic] remove ros_tutorials override.

- ros-catkin-build/melodic/build.rosinstall
The changes are merged by the upstream.
> remove vision_opencv override.

- ros-catkin-build/melodic/build.rosinstall
All changes are merged by the upstream.
> remove interactive_markers override.

- package-build/package-test-upgrade.yml
- ros-catkin-build/azure-pipelines.yml
> [melodic] add upgrade testing

- ros-colcon-build/eloquent/build.rosinstall
* Override `geometry2` to land this change https://github.com/ros2/geometry2/pull/247 first before it is resolved by the upstream.
> [eloquent] override geometry2

- ros-colcon-build/dashing/azure-pipelines.yml
- ros-colcon-build/eloquent/azure-pipelines.yml
- ros-colcon-build/foxy/azure-pipelines.yml
skip the packages not for Windows.
> [ROS2] ignore non-windows packages.

- package-build/template.nuspec
- package-build/tools/chocolateyInstall.ps1
- package-build/tools/vcpkgInstall.ps1
* Fold vcpkg installation into the master package.
* Move the installation script to PowerShell, add more error handling and make it fail fast.
> [common] fold vcpkg installation into the master package.

- ros-colcon-build/dashing/azure-pipelines.yml
- ros-colcon-build/dashing/build.rosinstall
- ros-colcon-build/eloquent/azure-pipelines.yml
- ros-colcon-build/eloquent/build.rosinstall
- ros-colcon-build/foxy/azure-pipelines.yml
- ros-colcon-build/foxy/build.rosinstall
adding the new `msft_ros2_env` to bootstrap the environment.
> [ros2] adding msft_ros2_env.

- ros-catkin-build/melodic/build.rosinstall
- ros-colcon-build/noetic/build.rosinstall
The delta in `roscpp_core` and `ros_comm` have been merged by the upstream.
> [melodic][noetic] remove unused override.

- package-build/build.bat
- package-build/tools/vcpkgInstall.ps1
* Adding pointers to where to look for Vcpkg information.
* Disabling `USER_SITE` usage when running `rosdep`.
> [common] more reliability fixes.

- package-build/tools/checkEnvironment.ps1
- package-build/tools/chocolateyInstall.ps1
- package-build/tools/vcpkgInstall.ps1
- ros-catkin-build/common/checkout.yml
- ros-catkin-build/setup.bat
* Adding environment precheck: For examples, %PATH% length and Git existence.
* Adding Vcpkg upgrade path.
> [common] Vcpkg upgrade path and environment precheck

- ros-colcon-build/foxy/azure-pipelines.yml
- ros-colcon-build/foxy/build.rosinstall
bootstrap the build to `desktop`.
> [Foxy] Bootstrap to Desktop

- package-build/tools/vcpkgInstall.ps1
> [common] updated vcpkg 2020.06

- docker/melodic/windowsservercore/desktop-full/dockerfile
- gazebo/gazebo9/azure-pipelines.yml
- package-build/package-test-upgrade.yml
- package-build/package-test.yml
- ros-catkin-build/common/checkout.yml
- ros-colcon-build/common/checkout.yml
- sfx-installer/build.yml
Attempt to use the new feed url.
> [common] attempt to use the new feed url.

- common/agent-clean.yml
- common/agent-prep.yml
- docker/azure-pipelines.yml
- ros-catkin-build/azure-pipelines.yml
- ros-catkin-build/ros-melodic-desktop.runtests.yml
- ros-catkin-build/ros-melodic-desktop_full.runtests.yml
- ros-catkin-build/ros-melodic-ros_base.runtests.yml
- ros-colcon-build/crystal/azure-pipelines.yml
- ros-colcon-build/dashing/azure-pipelines.yml
- ros-colcon-build/eloquent/azure-pipelines.yml
- ros-colcon-build/foxy/azure-pipelines.yml
- ros-colcon-build/melodic/azure-pipelines.yml
- ros-colcon-build/noetic/azure-pipelines.yml
Recently all our build pipelines are running much slower. One delta is the agent CPU spec seems to be changed. I am collecting more agent information to help troubleshoot the slowness.
* Collect agent machine spec to help troubleshoot slow build issues.
> [common] Collecting agent information for troubleshooting

- docker/melodic/windowsservercore/desktop-full/dockerfile
- gazebo/gazebo9/azure-pipelines.yml
- package-build/package-test-upgrade.yml
- package-build/package-test.yml
- ros-catkin-build/common/checkout.yml
- ros-colcon-build/common/checkout.yml
- sfx-installer/build.yml
To be aligned with the new feed URL.
> [common] switch to the new alias.

- ros-colcon-build/common/checkout.yml
- ros-colcon-build/dashing/azure-pipelines.yml
- ros-colcon-build/dashing/build.rosinstall
- ros-colcon-build/eloquent/azure-pipelines.yml
- ros-colcon-build/eloquent/build.rosinstall
- ros-colcon-build/foxy/build.rosinstall
* Using the release branch for nightly build.
* Only keep the desktop matrix to be aligned with OR composition.
> [ROS2] Use the release branch for packages

- ros-colcon-build/dashing/azure-pipelines.yml
- ros-colcon-build/eloquent/azure-pipelines.yml
- ros-colcon-build/foxy/azure-pipelines.yml
Seed the build date into the release version to avoid Nuget package publish conflicts.
> [ROS2] Seed the build date

- ros-colcon-build/dashing/azure-pipelines.yml
- ros-colcon-build/eloquent/azure-pipelines.yml
- ros-colcon-build/foxy/azure-pipelines.yml
The characters are too long for Chocolatey package, so make it shorter.
> [ROS2] shorten the date string and make it the least significant part.

- experimental/ros/noetic/noetic_override.repos
picked the commit with the Windows port fix.
> [noetic] fix random_numbers.dll missing issue.

- experimental/ros/azure-pipelines.dashing.release.yml
- experimental/ros/azure-pipelines.eloquent.release.yml
- experimental/ros/azure-pipelines.foxy.release.yml
- experimental/ros/azure-pipelines.noetic.release.yml
Use the `resource` so that ADO can better track the cross pipeline history.
> [vNext] Use resource to better track cross pipeline history

- experimental/external/azure.pipelines.external.yml
Migrating to use the ADO resources for the external pipelines.
> [vNext] Use the resources for the external pipelines

- experimental/ros/azure-pipelines.publish.yml
Use different deployment environments, so the approvals & checks can go separately.
> [vNext] Use different deployment environments.

- experimental/test/azure-pipelines.ar-tu-do.yml
Adding `ar-tu-do` project into the CI pipelines targeting `Noetic` and the related port work is on the https://github.com/ms-iot/ros_simulation_lab repo.
> [Noetic] Adding ar-tu-do into the CI pipelines.

- experimental/external/azure-pipelines.external.melodic.yml
- experimental/external/melodic/vcpkg.in
- experimental/external/melodic/vcpkg.ps1
* Adding more libs from Vcpkg, so it will be on par with the last release `desktop_full` installation.
> [vNext][Melodic] Adding more libs from Vcpkg.

- experimental/ros/azure-pipelines.noetic.release.yml
- experimental/ros/noetic/build.bat
- experimental/ros/noetic/patch.bat
- experimental/ros/noetic/pre-patch/etc/ros/rosdep/sources.list.d/10-ms-iot.list
- experimental/ros/noetic/pre-patch/etc/ros/rosdep/windows.yaml
Adding the rosdep into the install layout.
> [vnext] [noetic] Adding rosdep integration

- README.md
Showing the latest release versions instead of the build status (which is less relevant to the users).
> [readme] Showing the latest release versions

- experimental/ros/foxy/build.bat
- experimental/ros/foxy/foxy_override.repos
Fix the moveit_core build break.
> [vNext][Foxy] Fix foxy build.

- experimental/README.md
Add examples for the team to look up later.
> [handbook] Add examples.

- ros/melodic/patch.bat
> [melodic] Lock Ninja version to 1.8.2.

- ros/noetic/build.bat
- ros/noetic/noetic.repos
Updated moveit versions to match latest tags and added ignore for moveit_resources_prbt_ikfast_manipulator_plugin.
> Updated moveit versions and added ignore for ikfast

- ros/azure-pipelines.noetic.release.yml
> Rev release version

- .gitignore
- ros/humble/patch/etc/ros/rosdep/sources.list.d/10-ms-iot.list
- ros/humble/patch/lib/cmake/gazebo/gazebo-config.cmake
- ros/humble/setup.iss
- ros/humble/src/msft_ros2_env/CMakeLists.txt
- ros/humble/src/msft_ros2_env/env-hooks/gazebo.dsv.in
- ros/humble/src/msft_ros2_env/env-hooks/make_vcpkg.bat.in
This also fixes some distro mismatches
> Support Adminless install
